[env]
platform = espressif32@6.12.0
platform_packages =
	platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b
	platformio/tool-esptoolpy@2.40900.250804
	platformio/tool-mkfatfs@2.0.1
	platformio/tool-mklittlefs@1.203.210628
	platformio/tool-mkspiffs@2.230.0

[env:esp32-s3-zero]
board = esp32-s3-zero
framework = arduino
board_build.mcu = esp32s3

monitor_speed = 115200

board_build.partitions = default.csv

build_type = release

build_flags =
	-I src/BrewManager
	-I src/ScaleManager
	-I src/WebApi

lib_deps =
	h2zero/NimBLE-Arduino@2.1.3
	adafruit/Adafruit NeoPixel@1.15.2
	ESP32Async/AsyncTCP@3.4.9
	ESP32Async/ESPAsyncWebServer@3.9.0
	ipdotsetaf/ESPAsyncHTTPUpdateServer@3.0.0
	bblanchon/ArduinoJson@7.4.2

[env:upesy_wroom]
board = upesy_wroom
framework = arduino

monitor_speed = 115200

board_build.partitions = default.csv

build_flags =
	-I src/BrewManager
	-I src/ScaleManager
	-I src/WebApi
	-DDEBUG_BUILD
	-DESPASYNCHTTPUPDATESERVER_DEBUG
    ; -D CORE_DEBUG_LEVEL=5
    ; -D CONFIG_NIMBLE_CPP_LOG_LEVEL=4

build_type = debug

lib_deps =
	h2zero/NimBLE-Arduino@2.3.6
	adafruit/Adafruit NeoPixel@1.15.2
	ESP32Async/AsyncTCP@3.4.9
	ESP32Async/ESPAsyncWebServer@3.9.0
	ipdotsetaf/ESPAsyncHTTPUpdateServer@3.0.0
	bblanchon/ArduinoJson@7.4.3
